const quizActionTypes = {
        LOAD_QUESTION_REQUEST: "LOAD_QUESTION_REQUEST",
        LOAD_QUESTION_SUCCEED: "LOAD_QUESTION_SUCCEED",
        LOAD_QUESTION_FAILURE: "LOAD_QUESTION_FAILURE",
        LOAD_QUESTION_RESULT_REQUEST: "LOAD_QUESTION_RESULT_REQUEST",
        LOAD_QUESTION_RESULT_SUCCEED: "LOAD_QUESTION_RESULT_SUCCEED",
        LOAD_QUESTION_RESULT_FAILURE: "LOAD_QUESTION_RESULT_FAILURE",
}
export default quizActionTypes;
