const userActionTypes = {
        USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
        USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
        USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
        USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
        USER_EXTERNAL_LOGIN_REQUEST: "USER_EXTERNAL_LOGIN_REQUEST",
        USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
        USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
        USER_LOGOUT_REQUESTED: "USER_LOGOUT_REQUESTED",
        USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
        USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
        FETCH_MYINFO_REQUESTED: "FETCH_MYINFO_REQUESTED",
        FETCH_MYINFO_SUCCEEDED: "FETCH_MYINFO_SUCCEEDED",
        FETCH_MYINFO_FAILURE: "FETCH_MYINFO_FAILURE",
}

export default userActionTypes